version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3001:3001
    environment:
      - DATABASE_HOST=mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ihelp:/data/db

volumes:
  ihelp: